spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow
    password: taskflow_local_dev
    hikari:
      maximum-pool-size: 5

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.security: TRACE
  pattern:
    correlation: "[%X{correlationId:-}] "